apiVersion: v1
kind: Namespace
metadata:
  name: gse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  namespace: gse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: crawler:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: POSTGRES_CONN
          value: "postgresql://postgres:toor@postgres:5432/gse"
        ports:
        - containerPort: 3000

