[package]
name = "rse_server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"

diesel = "2.1.3"
diesel-async = { version = "0.4.1", features = ["mysql"] }

actix-web = "4.4.0"
serde = { version = "1.0.189", features = ["derive"] }
