[package]
name = "error"
version = "0.1.0"
edition = "2021"

[dependencies]
# Error Handling
thiserror = "1.0.50"
serde = { version = "1.0.189", features = ["derive"] }

# HTTP
reqwest = "0.11.22"
url = "2.4.1"

# Database
diesel = "2.1.3"
