version: '3.8'

services:
  rse_server:
    build: ./rse_server
    container_name: rse_server
    restart: always
    environment:
        MYSQL_SERVER: 10.5.0.2
        MYSQL_PORT: 3306
        MYSQL_DATABASE: rse
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: toor
    depends_on:
      - 'database'
    networks:
      backend:
        ipv4_address: 10.5.0.3
  rse_crawler:
    build: ./rse_crawler
    container_name: rse_crawler
    restart: always
    environment:
        SEED_URLS: seed_urls.json
        MYSQL_SERVER: 10.5.0.2
        MYSQL_PORT: 3306
        MYSQL_DATABASE: rse
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: toor
    depends_on:
      - 'database'
    networks:
      backend:
        ipv4_address: 10.5.0.4
  database:
    image: mysql:8.1.0
    restart: always
    volumes:
      - ./database/storage:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: rse
    ports:
      - "3306:3306"
    networks:
      backend:
        ipv4_address: 10.5.0.2

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
