version: '3.8'

services:
  rse_server:
    build:
      context: .
      dockerfile: rse_server.Dockerfile
    container_name: rse_server
    restart: always
    env_file: ../.env
    depends_on:
      - 'database'
    ports:
      - '80:8080'
    networks:
      backend:
        ipv4_address: 10.5.0.3
      frontend:
  rse_crawler:
    build:
      context: .
      dockerfile: rse_crawler.Dockerfile
    container_name: rse_crawler
    restart: always
    env_file: ../.env
    depends_on:
      - 'database'
    networks:
      backend:
        ipv4_address: 10.5.0.4
  database:
    image: postgres:16.0
    container_name: rse_database
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: rse
    ports:
      - '5432:5432'
    networks:
      backend:
        ipv4_address: 10.5.0.2

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
  frontend:
    driver: bridge