[package]
name = "rse_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"

serde = "1.0.189"
serde_json = "1.0.107"
serde_yaml = "0.9.25"

mysql_async = "0.32.2"

spider = { version = "1.46.2", features = ["budget"] }
scraper = "0.17.1"

regex = "1.10.1"

sha256 = "1.4.0"

