[package]
name = "rse_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
# Logging
log = "0.4.20"
env_logger = "0.10.0"

# Async Runtime
tokio = { version = "1.33.0", features = ["full"] }

# Seed URLs
serde = "1.0.189"
serde_json = "1.0.107"
serde_yaml = "0.9.25"

# Database
# mysql_async = "0.32.2"
diesel = "2.1.3"
diesel-async = { version = "0.4.1", features = ["mysql"] }

# Crawler
num_cpus = "1.16.0"
# spider = { version = "1.46.2", features = ["budget"] }
# scraper = "0.17.1"
reqwest = { version = "0.11.22", features = ["blocking"] }
scraper = "0.17.1"
rayon = "1.8.0"
rust-stemmers = "1.2.0"

# Spider
spider = { version = "1.46.3", features = ["budget"] } #, "decentralized"] }
#spider_worker = { version = "1.46.3", features = ["full_resources"] }
async-recursion = "1.0.5"

[dev-dependencies]
color-eyre = "0.6.2"