[package]
name = "rse_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
# Logging
log = "0.4.20"
env_logger = "0.10.0"

# Async Runtime
tokio = { version = "1.33.0", features = ["full"] }

# Seed URLs
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"

# Database
db = { path = "db" }

# Crawler
